routes/web.php
<?php

include_once 'web_builder.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::pattern('slug', '[a-z0-9- _]+');

Route::group(['prefix' => 'admin', 'namespace'=>'Admin'], function () {

    # Error pages should be shown without requiring login
    Route::get('404', function () {
        return view('admin/404');
    });
    Route::get('500', function () {
        return view('admin/500');
    });
    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
    # All basic routes defined here
    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
    Route::post('signup', 'AuthController@postSignup')->name('admin.signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');
    Route::get('login2', function () {
        return view('admin/login2');
    });
//    Route::get('{provider}', 'AuthController@redirectToProvider');
//    Route::get('{provider}/callback', 'AuthController@handleProviderCallback');



    # Register2
    Route::get('register2', function () {
        return view('admin/register2');
    });
    Route::post('register2', 'AuthController@postRegister2')->name('register2');

    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});


Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    # GUI Crud Generator
    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('generator_builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');
    // Model checking
    Route::post('modelCheck', 'ModelcheckController@modelCheck');

    # Dashboard / Index
    Route::get('/', 'JoshController@showHome')->name('dashboard');
    # crop demo
    Route::post('crop_demo', 'JoshController@crop_demo')->name('crop_demo');
    //Log viewer routes
    Route::get('log_viewers', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@index')->name('log-viewers');
    Route::get('log_viewers/logs', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@listLogs')->name('log_viewers.logs');
    Route::delete('log_viewers/logs/delete', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@delete')->name('log_viewers.logs.delete');
    Route::get('log_viewers/logs/{date}', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@show')->name('log_viewers.logs.show');
    Route::get('log_viewers/logs/{date}/download', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@download')->name('log_viewers.logs.download');
    Route::get('log_viewers/logs/{date}/{level}', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@showByLevel')->name('log_viewers.logs.filter');
    Route::get('log_viewers/logs/{date}/{level}/search', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@search')->name('log_viewers.logs.search');
    Route::get('log_viewers/logcheck', '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@logCheck')->name('log-viewers.logcheck');
    //end Log viewer
    # Activity log
    Route::get('activity_log/data', 'JoshController@activityLogData')->name('activity_log.data');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
//    Route::get('/', 'JoshController@index')->name('index');
});

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {

    # User Management
    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
//        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
        Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');

    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    # Group Management
    Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

    /*routes for blog*/
    Route::group(['prefix' => 'blog'], function () {
        Route::get('{blog}/delete', 'BlogController@destroy')->name('blog.delete');
        Route::get('{blog}/confirm-delete', 'BlogController@getModalDelete')->name('blog.confirm-delete');
        Route::get('{blog}/restore', 'BlogController@restore')->name('blog.restore');
        Route::post('{blog}/storecomment', 'BlogController@storeComment')->name('storeComment');
    });
    Route::resource('blog', 'BlogController');

    /*routes for blog category*/
    Route::group(['prefix' => 'blogcategory'], function () {
        Route::get('{blogCategory}/delete', 'BlogCategoryController@destroy')->name('blogcategory.delete');
        Route::get('{blogCategory}/confirm-delete', 'BlogCategoryController@getModalDelete')->name('blogcategory.confirm-delete');
        Route::get('{blogCategory}/restore', 'BlogCategoryController@getRestore')->name('blogcategory.restore');
    });
    Route::resource('blogcategory', 'BlogCategoryController');
    /*routes for file*/
    Route::group(['prefix' => 'file'], function () {
        Route::post('create', 'FileController@store')->name('store');
        Route::post('createmulti', 'FileController@postFilesCreate')->name('postFilesCreate');
        Route::delete('delete', 'FileController@delete')->name('delete');
    });

    Route::get('crop_demo', function () {
        return redirect('admin/imagecropping');
    });


    /* laravel example routes */
    #Charts
    Route::get('laravel_chart', 'ChartsController@index')->name('laravel_chart');
    Route::get('database_chart', 'ChartsController@databaseCharts')->name('database_chart');

    # datatables
    Route::get('datatables', 'DataTablesController@index')->name('index');
    Route::get('datatables/data', 'DataTablesController@data')->name('datatables.data');

    # datatables
    Route::get('jtable/index', 'JtableController@index')->name('index');
    Route::post('jtable/store', 'JtableController@store')->name('store');
    Route::post('jtable/update', 'JtableController@update')->name('update');
    Route::post('jtable/delete', 'JtableController@destroy')->name('delete');



    # SelectFilter
    Route::get('selectfilter', 'SelectFilterController@index')->name('selectfilter');
    Route::get('selectfilter/find', 'SelectFilterController@filter')->name('selectfilter.find');
    Route::post('selectfilter/store', 'SelectFilterController@store')->name('selectfilter.store');

    # editable datatables
    Route::get('editable_datatables', 'EditableDataTablesController@index')->name('index');
    Route::get('editable_datatables/data', 'EditableDataTablesController@data')->name('editable_datatables.data');
    Route::post('editable_datatables/create', 'EditableDataTablesController@store')->name('store');
    Route::post('editable_datatables/{id}/update', 'EditableDataTablesController@update')->name('update');
    Route::get('editable_datatables/{id}/delete', 'EditableDataTablesController@destroy')->name('editable_datatables.delete');


    //tasks section
    Route::post('task/create', 'TaskController@store')->name('store');
    Route::get('task/data', 'TaskController@data')->name('data');
    Route::post('task/{task}/edit', 'TaskController@update')->name('update');
    Route::post('task/{task}/delete', 'TaskController@delete')->name('delete');

});

# This Route use for insert customer Identification  detail
Route::post('admin/insertIdentificationDetail', 'CustomerController@insertIdentificationDetail');
# Remaining pages will be called from below controller method
# in real world scenario, you may be required to define all routes manually

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {


    Route::get('{name?}', 'JoshController@showView');
});

#FrontEndController
Route::get('login', 'FrontEndController@getLogin')->name('login');
Route::post('login', 'FrontEndController@postLogin')->name('login');
Route::get('register', 'FrontEndController@getRegister')->name('register');

app/Models/Notary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;



class Notary extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    public $table = 'notarys';
    


    public $fillable = [
        'first_name',
        'second_name',
        'third_name',
        'fourth_name',
        'address',
        'district',
        'sub_division',
        'email',
        'contact_number',
        'notary_number',
        'notary_expiry_date',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'first_name' => 'string',
        'second_name' => 'string',
        'third_name' => 'string',
        'fourth_name' => 'string',
        'address' => 'string',
        'city' => 'string',
        'state' => 'string',
        'notary_number' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'first_name' => 'required',
        'second_name' => 'required',
        'address' => 'required'
    ];
    
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->second_name} {$this->third_name} {$this->fourth_name}";
    }    
}

resources/views/admin/transactions/create.blade.php
@extends('admin/layouts/default')

@section('title')
Transaction
@parent
@stop

@section('content')
@include('core-templates::common.errors')
<section class="content-header">
    <h1>Transaction</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Transactions</li>
        <li class="active">Create Transaction </li>
    </ol>
</section>
<section class="content paddingleft_right15">
<div class="row">
 <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"> <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                Create New  Transaction
            </h4></div>
        <br />
        <div class="panel-body">
        {!! Form::open(['route' => 'admin.transactions.store']) !!}

            @include('admin.transactions.fields')

        {!! Form::close() !!}
    </div>
  </div>
 </div>
</section>
 @stop
@section('footer_scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $("form").submit(function() {
                $('input[type=submit]').attr('disabled', 'disabled');
                return true;
            });
        });
    </script>
@stop

resources/views/admin/transactions/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.transactions.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.transactions.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('admin.transactions.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/transactions/fields.blade.php
<!-- Service Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('service_id', 'Service Id:') !!}
    {!! Form::text('service_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Application Date Field -->
<div class="form-group col-sm-12">
    {!! Form::label('application_date', 'Application Date:') !!}
    {!! Form::date('application_date', null, ['class' => 'form-control']) !!}
</div>

<!-- Buyer Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('buyer_id', 'Buyer Id:') !!}
    {!! Form::text('buyer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Seller Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('seller_id', 'Seller Id:') !!}
    {!! Form::text('seller_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Property Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('property_id', 'Property Id:') !!}
    {!! Form::text('property_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Sale Date Field -->
<div class="form-group col-sm-12">
    {!! Form::label('settlement_date', 'Settlement Date:') !!}
    {!! Form::date('settlement_date', null, ['class' => 'form-control']) !!}
</div>

<!-- Sale Amount Field -->
<div class="form-group col-sm-12">
    {!! Form::label('settlement_amount', 'Settlement Amount:') !!}
    {!! Form::text('settlement_amount', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-12">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12 text-center">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.transactions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/transactions/index.blade.php
@extends('admin/layouts/default')

@section('title')
Transactions
@parent
@stop

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Transactions</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Transactions</li>
        <li class="active">Transactions List</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
     @include('flash::message')
        <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Transactions List
                </h4>
                <div class="pull-right">
                    <a href="{{ route('admin.transactions.create') }}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> @lang('button.create')</a>
                </div>
            </div>
            <br />
            <div class="panel-body table-responsive">
                 @include('admin.transactions.table')
                 
            </div>
        </div>
 </div>
</section>
@stop

resources/views/admin/transactions/invoice-payment-partial.blade.php
<div  class="row ">
    <div class="col-md-6">
        <h4>Invoice Details</h4>
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive">                                
        <table class="table table-bordered table-striped" >
            <tr>
                <td>Invoice No</td>
                <td>{{  $transaction->erp_invoice_id }}</td>
            </tr>                                   
        </table>
            @include("admin.invoice.invoice-items-table")
        </div>
    </div>
    <div class="col-md-6">
        <h4>Payment Details</h4>
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive"> 
        <table class="table table-bordered table-striped" >
        @if (isset($transaction->erp_payment_id))
            <tr>
                <td>Payment Receipt No </td>
                <td><b>{{ $transaction->erp_payment_id }}</b></td>
            </tr>
            <tr>
                <td>Payment Date </td>
                <td><b>{{ $transaction->payment_date }}</b></td>
            </tr>   
            <tr>
                <td>Payment Method </td>
                <td><b>{{ $transaction->payment_method }}</b></td>
            </tr>   
            <tr>
                <td>Payment Reference No </td>
                <td><b>{{ $transaction->payment_reference_number }}</b></td>
            </tr>                                    
        @endif
        </table>
        </div>
    </div>                            
</div>

resources/views/admin/transactions/show.blade.php
@extends('admin/layouts/default')

@section('title')
Transaction
@parent
@stop


{{-- page level styles --}}
@section('header_styles')
    <link href="{{ asset('assets/css/pages/invoice.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('assets/css/pages/wall_transaction.css') }}" rel="stylesheet" type="text/css"/>
@stop

@section('content')
<section class="content-header">
    <h1>Transaction View</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Transactions</li>
        <li class="active">View Transaction</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="panel panel-primary" id="hidepanel1">
    <div class="row">
            <div class="bs-example">
                <ul class="nav nav-tabs" style="margin-bottom: 15px;">
                    <li class="active">
                        <a href="#transaction" data-toggle="tab">Transaction Details</a>
                    </li>
                    <li class="">
                        <a href="#comments" data-toggle="tab">Comments</a>
                    </li>
                    <li>
                        <a href="#documents" data-toggle="tab">Documents</a>
                    </li>
                    <li>
                        <a href="#workflow" data-toggle="tab">Workflow</a>
                    </li>                         
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade active in" id="transaction">
                        <div class="row">
                            <div class="pull-right" style="padding-right: 15px">
                                    {!! Form::model($transaction, ['route' => ['workflow.initiate', $transaction->id ], 'method' => 'post']) !!}
                                            @if (!isset($transaction->workflow_instance_id))
                                                {!! Form::submit('Submit', ['class' => 'btn btn-sm btn-responsive button-alignment btn-success']) !!}
                                            @endif                
                                        <a onclick="javascript:window.print();" class="btn btn-sm btn-responsive button-alignment btn-success">Print</a>         
                                    {!! Form::close() !!}
                            </div>
                        </div>                        
                        @include('admin.transactions.summary-partial') 
                    </div>
                    <div class="tab-pane fade" id="comments">
                    </div>
                    <div class="tab-pane fade" id="documents">
                    </div>
                    <div class="tab-pane fade" id="workflow">
                    </div>

                </div>
            </div>   
        </div>
    </div>             
    <div class="form-group">
           <a href="{!! route('admin.transactions.index') !!}" class="btn btn-default">Back</a>
    </div>
  </div>
</section>
@stop

resources/views/admin/transactions/transaction-comments.blade.php
<div  class="row ">
    <div class="col-md-12">
        @if ($assignedToCurrentUser)
        <div class="row">            
            <span class="pull-right">
                <a class="btn btn-section btn-raised btn-success btn-sm payment-modal-button" data-transaction-id="{{ $transaction->id }}" data-toggle="modal" data-href="#transaction-comment-div" href="#transaction-comment-div" id="transaction-coomment-add-button">add</a><p></p>
            </span>
        </div>  
        @endif
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive"> 
        <table class="table table-bordered table-striped" width="100%" id="transaction-comments-table" >
            <thead><tr>
                    <th width="15%">Date</th>
                    <th>Comments</th>
                    <th width="15%">Updated By</th>
                    <th width="2%">Action</th>
                </tr>
            @if (isset($transactionComments))
            <tbody>
                @foreach($transactionComments as $comments)
                <tr>
                    <td>{{ Carbon\Carbon::parse($comments->created_at)->format('d M Y  h:i a') }}</td>
                    <td>{{ $comments->comments }} </td>
                    <td>{{ $comments->updatedBy->full_name }} </td>
                    <td>
                        <a href="#" data-action="{{ route("admin.transaction.comments.delete", $comments->id) }}" data-toggle="modal" data-target="#delete-confirmation-modal">
                            <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete"></i>
                        </a>
                    </td>                    
                </tr>
                @endforeach
            </tbody>
            @endif
        </table>
        </div>
    </div>                            
</div>

resources/views/admin/transactions/transaction-customer-details.blade.php
<div  class="row ">
    <div class="col-md-6">
        <h4>Seller Details</h4>
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive">                                
        <table class="table table-bordered table-striped" >
            <tr>
                <td>Sellers</td>
                <td>
                    @if($property->currentowners)
                        @foreach($property->currentowners as $owner)
                            {{ $owner->customer->full_name }} 
                            @if($owner->primary_owner == 'Yes') [P] @endif <br/>
                        @endforeach
                    @endif                                            
                </td>
            </tr>
            <tr>
                <td>Purchase Date</td>
                <td>
                    @if($property->currentowners) 
                        {{date('d F Y', strtotime($property->currentowners[0]->purchase_date))}}
                    @endif
                </td>
            </tr>     
            <tr>
                <td>Purchase Date</td>
                <td>
                    @if($property->currentowners) 
                        $ {{$property->currentowners[0]->purchase_price }}
                    @endif
                </td>
            </tr>                                     
        </table>
        </div>
    </div>
    <div class="col-md-6">
        <h4>Buyer Details</h4>
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive">                                
        <table class="table table-bordered table-striped" >
            <tr>
                <td>Buyers</td>
                <td>
                    @if($propertyOwnershipApplication)
                        @foreach($propertyOwnershipApplication as $buyer)
                            {{ $buyer->customer->full_name }} 
                            @if ($buyer->customer->id == $transaction->buyer_id) [P] @endif <br/>
                        @endforeach
                    @endif                                            
                </td>
            </tr>   
        </table>
        </div>
    </div>                            
</div>

resources/views/admin/transactions/transaction-documents.blade.php
<div  class="row ">
    <div class="col-md-12">
        @if ($assignedToCurrentUser)
        <div class="row">
            <span class="pull-right">
                <a class="btn btn-section btn-raised btn-success btn-sm payment-modal-button" data-transaction-id="{{ $transaction->id }}" data-toggle="modal" data-href="#transaction-document-div" href="#transaction-document-div" id="transaction-document-add-button">add</a><p></p>
            </span>
        </div>
        @endif
        <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive"> 
        <table class="table table-bordered table-striped" >
            <thead><tr>
                    <th width="15%">Date</th>
                    <th>Document</th>
                    <th width="15%">Updated By</th>
                    <th width="2%">Action</th>
                </tr>
            @if (isset($transactionDocuments))
            <tbody>
                @foreach($transactionDocuments as $document)
                <tr>
                    <td>{{ Carbon\Carbon::parse($document->created_at)->format('d M Y  h:i a') }}</td>
                    <td>{{ $document->documentType->Name }} </td>
                    <td>{{ $document->updatedBy->full_name }} </td>
                    <td>
                        <a href="#" data-action="{{ route("admin.transaction.document.delete", $document->id) }}" data-toggle="modal" data-target="#delete-confirmation-modal">
                            <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete document"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
            @endif
        </table>
        </div>
    </div>                            
</div>

resources/views/admin/transactions/transaction-history.blade.php
<div class="row">
    <div id="transaction-history-partial-div" id="printSection">    
        <section class="content paddingleft_right15">        
            <div class="row">    
                <div class="panel panel-info">
                    <div class="panel-heading clearfix">
                        <h4 class="panel-title"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                            Workflow History 
                        </h4>
                        <span class="pull-right ">
                            <a href='#' id="workflow-history" style='color:#fff'><i class="fa fa-chevron-down"></i></a>
                        </span>
                    </div>
                    <div class="panel-body" style="display: none">
                        <section class="content">
                            <div class="table-responsive-lg table-responsive-sm table-responsive-md table-responsive"> 
                                <table class="table table-bordered table-striped" width="100%" id="workflow-history-table" >
                                    <thead><tr>                                                
                                            <th width="5%"></th>
                                            <th>Workflow Step</th>
                                            <th>User</th>
                                            <th width="15%">Assigned Date</th>
                                            <th width="15%">Start Date</th>
                                            <th width="15%">Completed Date</th>
                                        </tr>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    </div>                            
                </div>
        </section>
    </div>
</div>

resources/views/admin/transactions/wall_transaction.blade.php
@extends('admin/layouts/default')

@section('title')
Transactions
@parent
@stop

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Transactions</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Transactions</li>
        <li class="active">Transactions Wall</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
     @include('flash::message')
        <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Transactions Wall
                </h4>
                <div class="pull-right">
                    <a href="{{ route('admin.transactions.create') }}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> @lang('button.create')</a>
                </div>
            </div>
            <br />
            <div class="panel-body table-responsive">
                 @include('admin.transactions.view_wall_transaction')
                 
            </div>
        </div>
 </div>
</section>
@stop